modelRoles:
  default: spark-node-01/q38fn:low
  smol: spark-node-01/q38fn:low
  slow: spark-node-01/q38fn:low
  plan: spark-node-01/q38fn:low
  commit: spark-node-01/q38fn:low
  designer: spark-node-01/q38fn:low
  advisor: spark-node-01/q38fn:low
  tiny: spark-node-01/q38fn:low
  vision: spark-node-01/q38fn:low
  task: spark-node-01/q38fn:low
defaultThinkingLevel: auto
hideThinkingBlock: true
startup:
  setupWizard: false
setupVersion: 1
compaction:
  strategy: context-full
providers:
  streamFirstEventTimeoutSeconds: 1800
  streamIdleTimeoutSeconds: 1800
