import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { gatewayRequest, resolveAdminCredential, redactGatewaySecrets } from './gateway-client.mjs';
import { currentNodeId, runtimePlacement } from './cluster.mjs';

const execAsync = promisify(execFile);
const exec = (file, args) => execAsync(file, args, { timeout: 15000, maxBuffer: 1024 * 1024 });

// Linux *user* systemd only. The unit name is fixed so an operator can never
// point this at an arbitrary or system-scope unit, and every command below runs
// against `systemctl --user` / the caller's own `loginctl` record without sudo.
export const SERVICE_UNIT_NAME = 'lloom.service';
export const SERVICE_MANAGER = 'systemd-user';
export const UNIT_OWNERSHIP_MARKER = '# lloom-managed-unit: lloom-user-service-v1';
export const DEFAULT_RESTART_SEC = 5;

const CONTROL_CHARACTERS = /[\u0000-\u001f\u007f]/;
const PERMISSION_FAILURE =
  /permission denied|authentication required|not permitted|access denied|polkit|interactive authentication/i;
const hash = (text) => createHash('sha256').update(text).digest('hex');

/** Absolute path of the installed CLI entrypoint this module was shipped with. */
export function defaultServiceEntrypoint() {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'bin', 'lloom.mjs');
}

export function serviceUnitPath(home) {
  return path.join(home, '.config', 'systemd', 'user', SERVICE_UNIT_NAME);
}

/**
 * Reject values that would corrupt a unit line before any side effect runs.
 *
 * Newlines, NUL, and other control characters can inject a new directive or
 * truncate the argv, so they are refused outright rather than escaped.
 */
export function assertSafeSystemdToken(value, label = 'value') {
  if (typeof value !== 'string' || value.length === 0) throw new Error(`${label} must be a non-empty string`);
  if (CONTROL_CHARACTERS.test(value))
    throw new Error(`${label} contains a control character, newline, or NUL and cannot be placed in a systemd unit`);
  return value;
}

/**
 * Quote one ExecStart token for systemd.
 *
 * systemd still expands `$VAR` and `%specifier` inside double quotes, so the
 * only safe literal escapes are `$$` and `%%`. Backslashes and quotes are
 * escaped for systemd's own parser, and the whole token is wrapped so spaces,
 * quotes, backticks, and semicolons stay a single literal argv element.
 * ExecStart is never run through a shell, so shell metacharacters are inert.
 */
export function systemdQuoteArg(value, label = 'unit argument') {
  assertSafeSystemdToken(value, label);
  const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '$$$$').replace(/%/g, '%%');
  return `"${escaped}"`;
}

/** Build the owned unit. Secrets are never inlined; only an environment-file path. */
export function buildServiceUnit({ nodePath, entryPath, configPath, environmentFile = null }) {
  const execStart = [
    systemdQuoteArg(nodePath, 'Node executable path'),
    systemdQuoteArg(entryPath, 'LLooM entrypoint path'),
    'serve',
    '--config',
    systemdQuoteArg(configPath, 'configuration path')
  ].join(' ');
  const lines = [
    '# Generated by `lloom service install`. Reinstalling this file replaces it.',
    UNIT_OWNERSHIP_MARKER,
    '[Unit]',
    'Description=LLooM local model gateway (user service)',
    'Wants=network-online.target',
    'After=network-online.target',
    'StartLimitIntervalSec=0',
    '',
    '[Service]',
    'Type=simple',
    `ExecStart=${execStart}`,
    'Restart=on-failure',
    `RestartSec=${DEFAULT_RESTART_SEC}`,
    'KillSignal=SIGTERM',
    'KillMode=process'
  ];
  if (environmentFile)
    lines.push(`EnvironmentFile=${systemdQuoteArg(environmentFile, 'environment file path').replaceAll('$$', '$')}`);
  lines.push('', '[Install]', 'WantedBy=default.target', '');
  return lines.join('\n');
}

export function isOwnedUnit(content) {
  return typeof content === 'string' && new RegExp(`^${UNIT_OWNERSHIP_MARKER}$`, 'm').test(content);
}

async function fileExists(target) {
  try {
    await fs.access(target);
    return true;
  } catch (error) {
    if (error.code === 'ENOENT') return false;
    throw error;
  }
}

async function readUnitFile(unitPath) {
  try {
    return await fs.readFile(unitPath, 'utf8');
  } catch (error) {
    if (error.code === 'ENOENT') return null;
    throw error;
  }
}

async function atomicWriteFile(target, content) {
  await fs.mkdir(path.dirname(target), { recursive: true });
  const tmp = `${target}.tmp-${process.pid}-${Date.now()}`;
  await fs.writeFile(tmp, content, { mode: 0o644 });
  await fs.rename(tmp, target);
}

function assertLinux(platform) {
  if (platform !== 'linux')
    throw new Error(
      'Service installation requires Linux user systemd; macOS launchd and system units are not supported'
    );
}

function assertApproval({ apply, yes }, action) {
  if (yes && !apply) throw new Error(`lloom service ${action} --yes requires --apply`);
  if (apply && !yes)
    throw new Error(`lloom service ${action} requires both --apply and --yes to change installed state`);
}

function withReceipt(error, receipt) {
  if (error && typeof error === 'object') error.receipt = receipt;
  return error;
}

/** Resolve the owned unit and its inputs without asserting a platform or writing. */
async function resolveServiceContext(config, options = {}) {
  const home = options.home ?? os.homedir();
  if (!home) throw new Error('Cannot determine the user home directory for the systemd user unit');
  const nodePath = path.resolve(options.nodePath ?? process.execPath);
  const entryPath = path.resolve(options.entryPath ?? defaultServiceEntrypoint());
  if (!config?.sourcePath) throw new Error('Configuration path is required to generate the service unit');
  const configPath = path.resolve(config.sourcePath);
  const requestedEnvironmentFile = options.environmentFile
    ? path.resolve(options.environmentFile)
    : path.join(home, '.config', 'lloom', 'env');
  const environmentFilePresent = await fileExists(requestedEnvironmentFile);
  if (options.environmentFile && !environmentFilePresent)
    throw new Error('The selected environment file does not exist');
  const environmentFile = environmentFilePresent ? requestedEnvironmentFile : null;
  let rawConfig = config.sourceTemplate ?? config;
  try {
    rawConfig = JSON.parse(await fs.readFile(configPath, 'utf8'));
  } catch (error) {
    if (!config.sourceTemplate) throw new Error('Cannot inspect the persistent configuration source', { cause: error });
  }
  const environmentRequired = configNeedsEnvironmentFile(rawConfig);
  const unitPath = serviceUnitPath(home);
  const content = buildServiceUnit({ nodePath, entryPath, configPath, environmentFile });
  const stat = await fs.lstat(unitPath).catch((error) => {
    if (error.code === 'ENOENT') return null;
    throw error;
  });
  if (stat && (!stat.isFile() || stat.isSymbolicLink())) throw new Error('Refusing a non-regular service unit');
  const existing = await readUnitFile(unitPath);
  const ownership = existing === null ? 'absent' : isOwnedUnit(existing) ? 'owned' : 'unowned';
  return {
    home,
    nodePath,
    entryPath,
    configPath,
    environmentFile,
    environmentFilePresent,
    environmentRequired,
    requestedEnvironmentFile,
    unitPath,
    content,
    unitHash: hash(content),
    existing,
    existingHash: existing === null ? null : hash(existing),
    ownership,
    uid: options.uid ?? process.getuid?.()
  };
}

async function planServiceUnit(config, options) {
  assertLinux(options.platform ?? process.platform);
  return await resolveServiceContext(config, options);
}

/** Read `Linger` for the caller's numeric uid: enabled / disabled / unknown. */
export async function readLinger({ run = exec, uid } = {}) {
  if (!Number.isInteger(uid))
    return { uid: uid ?? null, status: 'unknown', enabled: null, value: null, supported: false };
  try {
    const { stdout } = await run('loginctl', ['show-user', String(uid), '--property=Linger', '--value']);
    const value = String(stdout ?? '')
      .trim()
      .toLowerCase();
    if (value === 'yes') return { uid, status: 'enabled', enabled: true, value, supported: true };
    if (value === 'no') return { uid, status: 'disabled', enabled: false, value, supported: true };
    return { uid, status: 'unknown', enabled: null, value: value || null, supported: true };
  } catch (error) {
    const text = `${error?.message ?? error} ${error?.stderr ?? ''}`;
    return {
      uid,
      status: 'unknown',
      enabled: null,
      value: null,
      supported: true,
      error: String(error?.message ?? error),
      permissionFailure: PERMISSION_FAILURE.test(text)
    };
  }
}

/**
 * Install the owned user unit.
 *
 * Dry run by default; apply requires both `--apply` and `--yes`. The unit is
 * written atomically, and any failure after the write rolls back to the exact
 * previous unit (or removes a brand-new file) before a daemon-reload. When the
 * rollback itself fails, an explicit partial-failure receipt is attached.
 */
async function assertUnchanged(plan, expected = plan.existingHash) {
  const latest = await readUnitFile(plan.unitPath);
  if ((latest === null ? null : hash(latest)) !== expected)
    throw new Error('Installed unit changed concurrently; refusing to overwrite it');
}

// A per-user exclusive file prevents concurrent LLooM installers. A crash
// leaves the lock for operator inspection; we never guess whether it is stale.
async function withServiceLock(plan, action) {
  await fs.mkdir(path.dirname(plan.unitPath), { recursive: true });
  const lockPath = `${plan.unitPath}.lock`;
  const lock = await fs.open(lockPath, 'wx', 0o600).catch((error) => {
    if (error.code === 'EEXIST')
      throw new Error(`Service operation lock exists: ${lockPath}; inspect the previous operation before removing it`);
    throw error;
  });
  try {
    await lock.writeFile(JSON.stringify({ pid: process.pid, startedAt: new Date().toISOString() }));
    return await action();
  } finally {
    await lock.close();
    await fs.unlink(lockPath);
  }
}

async function readServiceState(run, plan) {
  const { stdout } = await run('systemctl', [
    '--user',
    'show',
    SERVICE_UNIT_NAME,
    '--property=ActiveState',
    '--property=UnitFileState',
    '--property=MainPID',
    '--property=LoadState',
    '--property=FragmentPath',
    '--property=DropInPaths'
  ]);
  const values = parseSystemdShow(stdout);
  if (values.LoadState === 'not-found') return { active: false, enabled: false };
  if (values.FragmentPath !== plan.unitPath || values.DropInPaths)
    throw new Error(
      'The loaded service is not the owned unit, or has drop-in overrides; operator migration is required'
    );
  if (!['active', 'inactive', 'failed'].includes(values.ActiveState) || !values.UnitFileState)
    throw new Error('Cannot establish a stable service state; retry after the service transition finishes');
  return { active: values.ActiveState === 'active', enabled: values.UnitFileState === 'enabled' };
}

export async function installGatewayService(config, options = {}) {
  const { apply = false, yes = false, enableLinger = false, expectedUnitHash, run = exec } = options;
  assertApproval({ apply, yes }, 'install');
  const plan = await planServiceUnit(config, options);
  const report = {
    action: 'install',
    service: SERVICE_UNIT_NAME,
    manager: SERVICE_MANAGER,
    unitPath: plan.unitPath,
    unitHash: plan.unitHash,
    existingHash: plan.existingHash,
    ownership: plan.ownership,
    config: plan.configPath,
    entrypoint: plan.entryPath,
    environmentFile: plan.environmentFile,
    changed: plan.existingHash !== plan.unitHash,
    applied: false,
    preserveRuntimes: true,
    enableLinger: Boolean(enableLinger)
  };
  if (!apply) return { ...report, ...(plan.ownership === 'unowned' ? { refusal: 'unowned' } : {}) };
  if (plan.ownership === 'unowned') throw new Error('Refusing to replace an unowned service unit');
  if (plan.environmentRequired && !plan.environmentFilePresent)
    throw new Error('Configuration contains environment placeholders but no persistent environment file exists');
  if (expectedUnitHash !== undefined && expectedUnitHash !== plan.existingHash)
    throw new Error('Installed unit changed since the reviewed plan');
  return withServiceLock(plan, async () => {
    await assertUnchanged(plan);
    const previous = await readServiceState(run, plan);
    // Replacing a running unit does not replace its process. Do not report the
    // new executable/config as active or restart it without a request drain.
    if (previous.active && report.changed)
      throw new Error(
        'The running service differs from this install plan; drain and stop the gateway before replacing its unit'
      );
    let linger = await readLinger({ run, uid: plan.uid });
    if (linger.enabled !== true) {
      if (!enableLinger)
        throw new Error('Persistence is not verified: review and repeat with --enable-linger --apply --yes');
      if (!Number.isInteger(plan.uid)) throw new Error('Cannot enable lingering without a numeric user id');
      try {
        await run('loginctl', ['enable-linger', String(plan.uid)]);
      } catch {
        throw new Error(
          'loginctl could not enable lingering; use an authorized login session to enable it, then retry (no sudo is used)'
        );
      }
      linger = await readLinger({ run, uid: plan.uid });
      if (linger.enabled !== true) throw new Error('Linger verification failed; service installation was not started');
    }
    let backupPath = null;
    if (plan.existing !== null) {
      const backupDir = path.join(plan.home, '.config', 'lloom', 'service-backups');
      await fs.mkdir(backupDir, { recursive: true, mode: 0o700 });
      backupPath = path.join(backupDir, `${SERVICE_UNIT_NAME}.${process.pid}.${Date.now()}.before`);
      await fs.writeFile(backupPath, plan.existing, { mode: 0o600, flag: 'wx' });
    }
    const steps = [];
    let wrote = false;
    let enableAttempted = false;
    let startAttempted = false;
    let failedStep = 'write-unit';
    let verification;
    try {
      await assertUnchanged(plan);
      if (report.changed) {
        await atomicWriteFile(plan.unitPath, plan.content);
        wrote = true;
        steps.push('write-unit');
      }
      failedStep = 'daemon-reload';
      await run('systemctl', ['--user', 'daemon-reload']);
      steps.push(failedStep);
      failedStep = 'enable';
      enableAttempted = true;
      await run('systemctl', ['--user', 'enable', SERVICE_UNIT_NAME]);
      steps.push(failedStep);
      failedStep = 'start';
      startAttempted = true;
      await run('systemctl', ['--user', 'start', SERVICE_UNIT_NAME]);
      steps.push(failedStep);
      failedStep = 'verify';
      const deadline = Date.now() + (options.startupTimeoutMs ?? 15000);
      do {
        verification = await doctorGatewayService(config, options);
        if (verification.ok || !['refused', 'timeout'].includes(verification.gateway.kind) || Date.now() >= deadline)
          break;
        await new Promise((resolve) => setTimeout(resolve, 100));
      } while (true);
      if (!verification.ok) throw new Error('Service verification failed');
      steps.push('verify');
    } catch (error) {
      const recovery = [];
      const failures = [];
      const recover = async (name, action) => {
        try {
          await action();
          recovery.push(name);
        } catch {
          failures.push(name);
        }
      };
      // A failed command may already have taken effect. Restore the recorded
      // state even when enable/start failed before returning a receipt.
      if (startAttempted && !previous.active)
        await recover('stop', () => run('systemctl', ['--user', 'stop', SERVICE_UNIT_NAME]));
      if (enableAttempted && !previous.enabled)
        await recover('disable', () => run('systemctl', ['--user', 'disable', SERVICE_UNIT_NAME]));
      if (wrote)
        await recover('restore-unit', async () => {
          await assertUnchanged(plan, plan.unitHash);
          if (plan.existing === null) await fs.unlink(plan.unitPath);
          else await atomicWriteFile(plan.unitPath, plan.existing);
        });
      await recover('daemon-reload', () => run('systemctl', ['--user', 'daemon-reload']));
      throw withReceipt(
        new Error(
          `Service install failed at ${failedStep}; ${failures.length ? 'recovery needs operator attention' : 'previous unit state restored'}`,
          { cause: error }
        ),
        {
          ...report,
          failedStep,
          completedSteps: steps,
          recovery,
          recoveryFailures: failures,
          verification,
          rollbackComplete: failures.length === 0,
          backupPath,
          linger
        }
      );
    }
    return { ...report, applied: true, steps, backupPath, linger, verification };
  });
}

/** Stop only the owned gateway unit. Never stops runtimes or arbitrary PIDs. */
export async function stopGatewayService(config, options = {}) {
  const { apply = false, yes = false, run = exec } = options;
  assertApproval({ apply, yes }, 'stop');
  const plan = await planServiceUnit(config, options);
  const report = {
    action: 'stop',
    service: SERVICE_UNIT_NAME,
    manager: SERVICE_MANAGER,
    platform: options.platform ?? process.platform,
    unitPath: plan.unitPath,
    ownership: plan.ownership,
    applied: false
  };
  if (!apply)
    return {
      ...report,
      wouldStop: plan.ownership === 'owned',
      ...(plan.ownership === 'owned' ? {} : { reason: plan.ownership === 'absent' ? 'not-installed' : 'unowned' })
    };
  if (plan.ownership !== 'owned')
    throw new Error(
      plan.ownership === 'absent'
        ? `No ${SERVICE_UNIT_NAME} unit is installed at ${plan.unitPath}`
        : `Refusing to stop unowned unit ${plan.unitPath}; it was not generated by lloom service install`
    );
  return withServiceLock(plan, async () => {
    await assertUnchanged(plan);
    await readServiceState(run, plan);
    await run('systemctl', ['--user', 'stop', SERVICE_UNIT_NAME]);
    return { ...report, applied: true, stopped: true };
  });
}

/**
 * Remove the owned unit with an accurate failure order and a retained receipt.
 *
 * Linger is intentionally never changed here so removing the service cannot
 * silently disable persistence an operator set up for other reasons.
 */
export async function uninstallGatewayService(config, options = {}) {
  const { apply = false, yes = false, run = exec } = options;
  assertApproval({ apply, yes }, 'uninstall');
  const plan = await planServiceUnit(config, options);
  const report = {
    action: 'uninstall',
    service: SERVICE_UNIT_NAME,
    manager: SERVICE_MANAGER,
    platform: options.platform ?? process.platform,
    unitPath: plan.unitPath,
    ownership: plan.ownership,
    lingerUnchanged: true,
    applied: false
  };
  if (!apply)
    return {
      ...report,
      wouldRemove: plan.ownership === 'owned',
      ...(plan.ownership === 'owned' ? {} : { reason: plan.ownership === 'absent' ? 'not-installed' : 'unowned' })
    };
  if (plan.ownership !== 'owned')
    throw new Error(
      plan.ownership === 'absent'
        ? `No ${SERVICE_UNIT_NAME} unit is installed at ${plan.unitPath}`
        : `Refusing to remove unowned unit ${plan.unitPath}; it was not generated by lloom service install`
    );
  return withServiceLock(plan, async () => {
    await assertUnchanged(plan);
    await readServiceState(run, plan);
    const receipt = {
      action: 'uninstall',
      service: SERVICE_UNIT_NAME,
      unitPath: plan.unitPath,
      steps: [],
      lingerUnchanged: true
    };
    const steps = [
      ['stop', () => run('systemctl', ['--user', 'stop', SERVICE_UNIT_NAME])],
      ['disable', () => run('systemctl', ['--user', 'disable', SERVICE_UNIT_NAME])],
      [
        'unlink',
        async () => {
          await assertUnchanged(plan);
          await fs.unlink(plan.unitPath);
        }
      ],
      ['daemon-reload', () => run('systemctl', ['--user', 'daemon-reload'])]
    ];
    for (const [name, step] of steps) {
      try {
        await step();
        receipt.steps.push(name);
      } catch (error) {
        receipt.failedStep = name;
        throw withReceipt(new Error(`service uninstall failed at ${name}: ${error?.message ?? error}`), receipt);
      }
    }
    return { ...report, applied: true, removed: true, steps: receipt.steps };
  });
}

export function dockerRuntimeIds(config, env = process.env) {
  return Object.entries(config?.runtimes ?? {})
    .filter(
      ([, runtime]) =>
        runtime &&
        runtime.enabled !== false &&
        runtimePlacement(runtime, config, env).node === currentNodeId(config, env) &&
        runtime.lifecycle !== 'external' &&
        (runtime.containerName || runtime.container?.name || runtime.adapter === 'docker')
    )
    .map(([id]) => id);
}

function configNeedsEnvironmentFile(config) {
  const { sourcePath: _sourcePath, ...rest } = config ?? {};
  return /\$\{[A-Za-z_][A-Za-z0-9_]*\}/.test(JSON.stringify(rest));
}

function localInterfaces() {
  return new Set(
    Object.values(os.networkInterfaces())
      .flat()
      .filter(Boolean)
      .map((entry) => entry.address)
  );
}

function parseSystemdShow(stdout) {
  const values = {};
  for (const line of String(stdout ?? '').split('\n')) {
    const index = line.indexOf('=');
    if (index === -1) continue;
    values[line.slice(0, index)] = line.slice(index + 1);
  }
  return values;
}

/**
 * Read-only structured service receipt.
 *
 * Ordinary absence (no unit, inactive, no linger, gateway down) is reported as
 * a failing check rather than thrown, but authentication/transport detail from
 * the shared gateway client stays stable so automation can branch on it.
 */
export async function doctorGatewayService(config, options = {}) {
  const platform = options.platform ?? process.platform;
  const run = options.run ?? exec;
  const fetchImpl = options.fetchImpl;
  const env = options.env ?? process.env;
  const home = options.home ?? os.homedir();
  const uid = options.uid ?? process.getuid?.();
  const timeoutMs = options.timeoutMs ?? 2000;
  const checks = [];
  const add = (id, ok, detail) => checks.push({ id, ok: Boolean(ok), detail });

  const ctx = await resolveServiceContext(config, options);
  const unitInstalled = ctx.ownership !== 'absent';
  const ownedAndMatching = ctx.ownership === 'owned' && ctx.existingHash === ctx.unitHash;

  add('platform-linux-user-systemd', platform === 'linux', `platform=${platform}`);
  add('unit-installed', unitInstalled, unitInstalled ? ctx.ownership : 'not installed');
  add('unit-owned', ctx.ownership === 'owned', `ownership=${ctx.ownership}`);
  add(
    'unit-config-match',
    ownedAndMatching,
    ownedAndMatching ? 'unit matches generated content' : `on-disk hash ${ctx.existingHash} vs expected ${ctx.unitHash}`
  );

  const systemd = {
    enabled: null,
    active: null,
    failed: null,
    restart: null,
    restartSec: null,
    mainPid: null,
    error: null
  };
  try {
    const result = await run('systemctl', [
      '--user',
      'show',
      SERVICE_UNIT_NAME,
      '--property=ActiveState',
      '--property=UnitFileState',
      '--property=Restart',
      '--property=RestartUSec',
      '--property=FragmentPath',
      '--property=DropInPaths',
      '--property=NeedDaemonReload',
      '--property=MainPID'
    ]);
    const props = parseSystemdShow(result?.stdout);
    systemd.fragmentPath = props.FragmentPath ?? null;
    systemd.dropInPaths = props.DropInPaths ?? null;
    systemd.needsReload = props.NeedDaemonReload ?? null;
    systemd.unitFileState = props.UnitFileState ?? null;
    systemd.activeState = props.ActiveState ?? null;
    systemd.enabled = props.UnitFileState === 'enabled';
    systemd.active = props.ActiveState === 'active';
    systemd.failed = props.ActiveState === 'failed';
    systemd.restart = props.Restart ?? null;
    systemd.restartSec = props.RestartUSec ?? null;
    systemd.mainPid = /^\d+$/.test(props.MainPID ?? '') ? Number(props.MainPID) : null;
  } catch (error) {
    systemd.error = String(error?.message ?? error);
  }
  add(
    'systemd-loaded-unit-match',
    systemd.fragmentPath === ctx.unitPath && systemd.dropInPaths === '' && systemd.needsReload === 'no',
    'loaded unit must match the owned file without drop-in overrides or pending reload'
  );
  add('systemd-enabled', systemd.enabled === true, `UnitFileState=${systemd.unitFileState ?? 'unknown'}`);
  add('systemd-active', systemd.active === true, `ActiveState=${systemd.activeState ?? 'unknown'}`);
  add(
    'systemd-not-failed',
    systemd.failed === false,
    systemd.error ? systemd.error : `ActiveState=${systemd.activeState ?? 'unknown'}`
  );
  add('systemd-restart-policy', systemd.restart === 'on-failure', `Restart=${systemd.restart ?? 'unknown'}`);

  const linger = await readLinger({ run, uid });
  add(
    'linger-enabled',
    linger.enabled === true,
    linger.permissionFailure
      ? `permission failure reading linger: ${linger.error}`
      : `loginctl reports Linger=${linger.value ?? linger.status}`
  );

  const bindHost = config.server?.host ?? '127.0.0.1';
  const wildcard = ['0.0.0.0', '::'].includes(bindHost);
  const loopback = ['127.0.0.1', '::1', 'localhost'].includes(bindHost);
  const interfaceAvailable = wildcard || loopback || (options.interfaces ?? localInterfaces()).has(bindHost);
  add(
    'bind-interface-available',
    interfaceAvailable,
    interfaceAvailable
      ? `${bindHost} is local to this host`
      : `configured interface ${bindHost} is not present on this host`
  );

  const expectedNodeId = currentNodeId(config, env);
  const gateway = {
    checked: true,
    reachable: false,
    kind: null,
    code: null,
    status: null,
    healthPid: null,
    unitPid: systemd.mainPid,
    pidMatches: null,
    expectedNodeId,
    observedNodeId: null,
    nodeIdMatch: null,
    detail: null,
    nodeError: null
  };
  let credential;
  let credentialError = null;
  try {
    credential = resolveAdminCredential(config, {
      explicitEnvName: options.adminKeyEnvName,
      env
    });
  } catch (error) {
    credentialError = error;
  }
  const headers = credential ? { authorization: `Bearer ${credential}` } : {};
  if (credentialError) {
    gateway.kind = 'auth';
    gateway.code = 'gateway_auth_failed';
    gateway.detail = credentialError.message;
  } else {
    try {
      if (!interfaceAvailable) throw new Error('Configured bind interface is absent; no gateway request was sent');
      const health = await gatewayRequest(config, '/health', {
        throwOnError: true,
        timeoutMs,
        headers,
        fetchImpl,
        env
      });
      gateway.reachable = health?.ok === true;
      gateway.healthPid = Number.isInteger(health?.pid) ? health.pid : null;
      if (gateway.healthPid !== null && gateway.unitPid !== null)
        gateway.pidMatches = gateway.healthPid === gateway.unitPid;
      try {
        const node = await gatewayRequest(config, '/gateway/node', {
          throwOnError: true,
          timeoutMs,
          headers,
          fetchImpl,
          env
        });
        gateway.observedNodeId = node?.node?.id ?? null;
        gateway.nodeIdMatch = expectedNodeId ? gateway.observedNodeId === expectedNodeId : null;
      } catch (error) {
        gateway.nodeError = {
          kind: error?.kind ?? null,
          code: error?.code ?? null,
          status: Number.isInteger(error?.status) ? error.status : null,
          message: error?.message ?? String(error)
        };
      }
    } catch (error) {
      gateway.kind = error?.kind ?? null;
      gateway.code = error?.code ?? null;
      gateway.status = Number.isInteger(error?.status) ? error.status : null;
      gateway.detail = error?.message ?? String(error);
    }
  }
  add(
    'gateway-reachable',
    gateway.reachable,
    gateway.reachable ? 'gateway answered /health' : (gateway.detail ?? 'unreachable')
  );
  add(
    'gateway-node-identity',
    gateway.nodeIdMatch === true,
    gateway.nodeIdMatch === true
      ? `gateway node ${gateway.observedNodeId} matches configuration`
      : `expected ${expectedNodeId ?? 'no configured cluster.nodeId'}, observed ${gateway.observedNodeId ?? gateway.nodeError?.code ?? 'unknown'}`
  );
  add(
    'gateway-pid-match',
    gateway.pidMatches === true,
    gateway.pidMatches === null
      ? 'pid comparison unavailable'
      : `health pid ${gateway.healthPid} vs unit pid ${gateway.unitPid}`
  );

  const needsEnvironmentFile = ctx.environmentRequired;
  add(
    'environment-file-present',
    !needsEnvironmentFile || ctx.environmentFilePresent,
    ctx.environmentFilePresent
      ? ctx.requestedEnvironmentFile
      : needsEnvironmentFile
        ? `missing ${ctx.requestedEnvironmentFile}`
        : 'not required by configuration'
  );

  const dockerIds = dockerRuntimeIds(config, env);
  const docker = { needed: dockerIds.length > 0, runtimeIds: dockerIds, available: null, version: null, error: null };
  if (docker.needed) {
    try {
      const result = await run('docker', ['version', '--format', '{{.Server.Version}}']);
      docker.available = true;
      docker.version = String(result?.stdout ?? '').trim() || null;
    } catch (error) {
      docker.available = false;
      docker.error = String(error?.message ?? error);
    }
  }
  add(
    'docker-available',
    docker.needed ? docker.available === true : true,
    docker.needed ? `required by runtimes ${dockerIds.join(', ')}` : 'no configured Docker runtimes'
  );

  const result = {
    ok: checks.every((check) => check.ok),
    service: {
      name: SERVICE_UNIT_NAME,
      manager: SERVICE_MANAGER,
      platform,
      unitPath: ctx.unitPath,
      installed: unitInstalled,
      ownership: ctx.ownership,
      hash: ctx.existingHash,
      expectedHash: ctx.unitHash,
      configMatch: ownedAndMatching,
      stale: ctx.ownership === 'owned' && ctx.existingHash !== ctx.unitHash
    },
    systemd,
    linger,
    bind: { host: bindHost, wildcard, loopback, interfaceAvailable },
    gateway,
    environmentFile: {
      path: ctx.requestedEnvironmentFile,
      present: ctx.environmentFilePresent,
      required: needsEnvironmentFile
    },
    docker,
    home,
    checks
  };
  function sanitize(value) {
    if (typeof value === 'string') return redactGatewaySecrets(value, { config, env, extraValues: [credential] });
    if (Array.isArray(value)) return value.map(sanitize);
    if (value && typeof value === 'object')
      return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, sanitize(item)]));
    return value;
  }
  return sanitize(result);
}
